% This function opens a subwindow and deal with fresco reconstruction
function [g_new_frags_sol,g_new_im_rec_color,g_new_im_rec_gray,g_rec_name] = arteak_reconstruction( fh_main )
    % We get GUI data
    g_mydata = guidata(fh_main);

    % We check if all inputs are available
    %if isempty(g_mydata.im_fresco) || isempty(g_mydata.frags_infos)
    %    uiwait(errordlg('A fresco image a set of fragment images must be previously loaded', 'ARTEAK ERROR', 'modal'));
    %    return;
    %end

    % We make as empty returned variables
    g_new_frags_sol    = {};
    g_new_im_rec_color = [];
    g_new_im_rec_gray  = [];
    g_rec_name         = '';

    % Global variables
    %[~,fresco_name,~] = fileparts(g_mydata.fresco_dir);
    %g_output_dir      = [g_mydata.output_root_dir filesep fresco_name];
    g_output_dir = ['toto est sympa ...'];

    g_general_parameters = {struct('name', 'output_dir', 'label', 'Output directory', 'type', 'string', 'value', g_output_dir), ...
                            struct('name', 'interpolation_type', 'label', 'Interpolation type', 'type', 'string', 'value', 'bilinear')};

    g_init_parameters = {struct('name', 'outside_fragment_tolerance', 'label', 'Outside fragment tolerance', 'type', 'numeric', 'value', '0.1', 'min', '0.0', 'max', '1.0'), ...
                         struct('name', 'fragments_overlap_tolerance', 'label', 'Fragments overlap tolerance', 'type', 'numeric', 'value', '0.1', 'min', '0.0', 'max', '1.0'), ...
                         struct('name', 'features_detection_threshold1', 'label', 'Features detection - threshold 1', 'type', 'numeric', 'value', '0.01', 'min', '0.0'), ...
                         struct('name', 'features_detection_threshold2', 'label', 'Features detection - threshold 2', 'type', 'numeric', 'value', '0.03', 'min', '0.0'), ...
                         struct('name', 'features_extraction_method', 'label', 'Features extraction - method', 'type', 'string', 'value', 'BRISK'), ...
                         struct('name', 'features_matching_threshold', 'label', 'Features matching - threshold', 'type', 'numeric', 'value', '50', 'min', '0.0', 'max', '50.0'), ...
                         struct('name', 'features_matching_max_ratio', 'label', 'Features matching - max ratio', 'type', 'numeric', 'value', '0.6', 'min', '0.0', 'max', '1.0'), ...
                         struct('name', 'features_matching_fresco_padding', 'label', 'Features matching - fresco padding', 'type', 'numeric', 'value', '18', 'min', '0'), ...
                         struct('name', 'features_matching_dilation_rate', 'label', 'Features matching - dilation rate', 'type', 'numeric', 'value', '0.5', 'min', '0.0', 'max', '1.0'), ...
                         struct('name', 'color_matching_nb_bins', 'label', 'Color matching - nb bins', 'type', 'numeric', 'value', '16', 'min', '1', 'max', '256'), ...
                         struct('name', 'color_matching_nb_rectangles', 'label', 'Color matching - nb rectangles', 'type', 'numeric', 'value', '1'), ...
                         struct('name', 'color_matching_dilatation_radius', 'label', 'Color matching - dilation radius', 'type', 'numeric', 'value', '3', 'min', '0'), ...
                         struct('name', 'color_matching_threshold', 'label', 'Color matching - threshold', 'type', 'numeric', 'value', '0.8', 'min', '0.0', 'max', '1.0')};

    g_mpp_parameters = {struct('name', 'beta_d', 'label', 'beta_{d}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                        struct('name', 'beta_inc', 'label', 'beta_{inc}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                        struct('name', 'beta_c', 'label', 'beta_{c}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                        struct('name', 'beta_no', 'label', 'beta_{no}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                        struct('name', 'beta_sf', 'label', 'beta_{sf}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                        struct('name', 'lambda', 'label', 'lambda', 'type', 'numeric', 'value', '1.0', 'min', '0.00000001'), ...
                        struct('name', 'mu', 'label', 'mu', 'type', 'numeric', 'value', '1.0', 'min', '-1.0', 'max', '1.0'), ...
                        struct('name', 'nb_iterations', 'label', 'Nb iterations', 'type', 'numeric', 'value', '1', 'min', '0'), ...
                        struct('name', 'nb_fragments', 'label', 'Nb fragments', 'type', 'numeric', 'value', '1', 'min', '1')};

    % We create the subwindow
    g_fh_rec = figure('menubar', 'none', ...
                      'toolbar', 'none', ...
                      'color', get(0, 'defaultuicontrolbackgroundcolor'), ...
                      'name', 'ARTEAK - Reconstruction', ...
                      'units', 'normalized', ...
                      'position', [0 0 1 1], ...
                      'closerequestfcn', @quit_callback);

    %-------------------------

    g_general_parameters_panel = uipanel('parent', g_fh_rec, ...
                                         'title', 'General parameters', ...
                                         'fontsize', 11, ...
                                         'fontweight', 'bold', ...
                                         'units', 'normalized', ...
                                         'position', [0.01 0.89 0.4 0.1]);

    g_general_parameters_label = cell(1,numel(g_general_parameters));
    g_general_parameters_edit  = cell(1,numel(g_general_parameters));

    for k=1:numel(g_general_parameters)
        g_general_parameters_label{k} = uicontrol('parent', g_general_parameters_panel, ...
                                                  'style', 'text', ...
                                                  'units', 'normalized', ...
                                                  'position', [0.01 0.6-(k-1)/numel(g_general_parameters) 0.5 0.3], ...
                                                  'fontsize', 11, ...
                                                  'horizontalalignment', 'right', ...
                                                  'string', [g_general_parameters{k}.label ':']);

         g_general_parameters_edit{k} = uicontrol('parent', g_general_parameters_panel, ...
                                                  'style', 'edit', ...
                                                  'tag', sprintf('general_%d', k), ...
                                                  'units', 'normalized', ...
                                                  'position', [0.55 0.6-(k-1)/numel(g_general_parameters)+0.02 0.4 0.3], ...
                                                  'fontsize', 11, ...
                                                  'string', g_general_parameters{k}.value, ...
                                                  'handlevisibility', 'callback', ...
                                                  'callback', @general_parameters_callback);
    end

    %-------------------------

    g_init_parameters_panel = uipanel('parent', g_fh_rec, ...
                                      'title', 'Initialization parameters', ...
                                      'fontsize', 11, ...
                                      'fontweight', 'bold', ...
                                      'units', 'normalized', ...
                                      'position', [0.01 0.43 0.4 0.45]);

    g_init_parameters_label = cell(1,numel(g_init_parameters));
    g_init_parameters_edit  = cell(1,numel(g_init_parameters));

    for k=1:numel(g_init_parameters)
        g_init_parameters_label{k} = uicontrol('parent', g_init_parameters_panel, ...
                                               'style', 'text', ...
                                               'units', 'normalized', ...
                                               'position', [0.01 0.92-(k-1)/numel(g_init_parameters) 0.6 0.06], ...
                                               'fontsize', 11, ...
                                               'horizontalalignment', 'right', ...
                                               'string', [g_init_parameters{k}.label ':']);

         g_init_parameters_edit{k} = uicontrol('parent', g_init_parameters_panel, ...
                                               'style', 'edit', ...
                                               'tag', sprintf('init_%d', k), ...
                                               'units', 'normalized', ...
                                               'position', [0.65 0.92-(k-1)/numel(g_init_parameters)+0.02 0.3 0.06], ...
                                               'fontsize', 11, ...
                                               'string', g_init_parameters{k}.value, ...
                                               'handlevisibility', 'callback', ...
                                               'callback', @init_parameters_callback);
    end

    %-------------------------

    g_mpp_parameters_panel = uipanel('parent', g_fh_rec, ...
                                      'title', 'MPP parameters', ...
                                      'fontsize', 11, ...
                                      'fontweight', 'bold', ...
                                      'units', 'normalized', ...
                                      'position', [0.42 0.59 0.4 0.4]);

    g_mpp_parameters_label = cell(1,numel(g_mpp_parameters));
    g_mpp_parameters_edit  = cell(1,numel(g_mpp_parameters));

    for k=1:numel(g_mpp_parameters)
        g_mpp_parameters_label{k} = uicontrol('parent', g_mpp_parameters_panel, ...
                                              'style', 'text', ...
                                              'units', 'normalized', ...
                                              'position', [0.01 0.92-(k-1)/numel(g_mpp_parameters) 0.6 0.06], ...
                                              'fontsize', 11, ...
                                              'horizontalalignment', 'right', ...
                                              'string', [g_mpp_parameters{k}.label ':']);

         g_mpp_parameters_edit{k} = uicontrol('parent', g_mpp_parameters_panel, ...
                                              'style', 'edit', ...
                                              'tag', sprintf('mpp_%d', k), ...
                                              'units', 'normalized', ...
                                              'position', [0.65 0.92-(k-1)/numel(g_mpp_parameters)+0.02 0.3 0.06], ...
                                              'fontsize', 11, ...
                                              'string', g_mpp_parameters{k}.value, ...
                                              'handlevisibility', 'callback', ...
                                              'callback', @mpp_parameters_callback);
    end

    %-------------------------

    g_h_reconstruct_button = uicontrol('parent', g_fh_rec, ...
                                       'units', 'normalized', ...
                                       'position', [0.01 0.06 0.3 0.04], ...
                                       'style', 'pushbutton', ...
                                       'fontsize', 11, ...
                                       'string', 'Reconstruct fresco', ...
                                       'handlevisibility', 'callback', ...
                                       'callback', @reconstruct_callback);

    g_h_quit_button = uicontrol('parent', g_fh_rec, ...
                                'units', 'normalized', ...
                                'position', [0.01 0.01 0.3 0.04], ...
                                'style', 'pushbutton', ...
                                'fontsize', 11, ...
                                'string', 'Quit', ...
                                'handlevisibility', 'callback', ...
                                'callback', @quit_callback);

    %---------------------------

    % We block the window
    uiwait(g_fh_rec);

    %----------------------------------------------------------------------
    %--------------------------- Non-callbacks ----------------------------
    %----------------------------------------------------------------------

    function err = manage_parameters( parameters_struct, parameters_str, h_object, event_data )
        tag   = str2num(get(h_object, 'tag'));
        input = strrep(get(h_object, 'string'), parameters_str, '');
        label = parameters_struct{tag}.label;
        err   = false;

        if strcmp(parameters_struct{tag}.type, 'numeric')
            input = str2num(input);

            if ~isnumeric(input)
                uiwait(errordlg(sprintf('Parameter %s must be numeric', label), 'ARTEAK ERROR', 'modal'));
                err = true;
                return;
            end

            if isfield(parameters_struct{tag}, 'min') && input<str2num(parameters_struct{tag}.min)
                uiwait(errordlg(sprintf('Parameter %s must be >= %f', label, parameters_struct{tag}.min), 'ARTEAK ERROR', 'modal'));
                err = true;
                return;
            end

            if isfield(parameters_struct{tag}, 'max') && input>str2num(parameters_struct{tag}.max)
                uiwait(errordlg(sprintf('Parameter %s must be <= %f', label, parameters_struct{tag}.max), 'ARTEAK ERROR', 'modal'));
                err = true;
                return;
            end
        elseif strcmp(parameters_struct{tag}.type, 'string')
            if isempty(input)
                uiwait(errordlg(sprintf('Parameter %s must be a non empty string', label), 'ARTEAK ERROR', 'modal'));
                err = true;
                return;
            end
        else
            uiwait(errordlg(sprintf('Unknown type for parameter %s', label), 'ARTEAK ERROR', 'modal'));
            err = true;
            return;
        end
    end

    %----------------------------------------------------------------------
    %----------------------------- Callbacks ------------------------------
    %----------------------------------------------------------------------

    function err = general_parameters_callback( h_object, event_data )
        err = manage_parameters(g_general_parameters, 'general', h_object, event_data);
    end

    function err = init_parameters_callback( h_object, event_data )
        err = manage_parameters(g_init_parameters, 'init', h_object, event_data);
    end

    function err = mpp_parameters_callback( h_object, event_data )
        err = manage_parameters(g_mpp_parameters, 'mpp', h_object, event_data);
    end

    function reconstruct_callback( h_object, event_data )
        % We first check parameters
        for k=1:numel(g_general_parameters)
            if general_parameters_callback(g_general_parameters_edit{k}, [])
                return;
            end
        end

        for k=1:numel(g_init_parameters)
            if init_parameters_callback(g_init_parameters_edit{k}, [])
                return;
            end
        end

        for k=1:numel(g_mpp_parameters)
            if mpp_parameters_callback(g_mpp_parameters_edit{k}, [])
                return;
            end
        end

        % Then, we run fresco reconstruction and set output variables
        g_new_frags_sol    = g_mydata.frags_sols{g_mydata.current_recs_idx};
        g_new_im_rec_color = g_mydata.im_recs_color{g_mydata.current_recs_idx};
        g_new_im_rec_gray  = g_mydata.im_recs_gray{g_mydata.current_recs_idx};
        g_rec_name         = get(g_general_parameters_edit{k}, 'string');
        close(g_fh_rec);
    end

    function quit_callback( h_object, event_data )
        delete(g_fh_rec);
    end
end