% This function opens a subwindow and deal with displaying measurements for a reconstructed fresco
function arteak_measurements( fh_main )
    % We get GUI data
    g_mydata = guidata(fh_main);

    % We check if all inputs are available
    if numel(g_mydata.frags_sols)<1
        uiwait(errordlg('At least one reconstructed fresco must be previsously loaded and selected', 'ARTEAK ERROR', 'modal'));
        return;
    end

    % We compute measurements
    [frags_cover_rate,frags_size,frags_contrast] = compute_measurements();

    % We create the subwindow
    g_fh_msm = figure('menubar', 'none', ...
                      'toolbar', 'none', ...
                      'color', get(0, 'defaultuicontrolbackgroundcolor'), ...
                      'name', 'ARTEAK - Measurements', ...
                      'units', 'normalized', ...
                      'position', [0 0 1 1], ...
                      'closerequestfcn', @quit_callback);

    g_h_quit_button = uicontrol('parent', g_fh_msm, ...
                                'units', 'normalized', ...
                                'position', [0.01 0.01 0.15 0.04], ...
                                'style', 'pushbutton', ...
                                'fontsize', 11, ...
                                'string', 'Quit', ...
                                'handlevisibility', 'callback', ...
                                'callback', @quit_callback);

    %---------------------------

    g_h_cover_rate_panel = uipanel('parent', g_fh_msm, ...
                                   'title', 'Cover rate of fragments', ...
                                   'fontsize', 11, ...
                                   'fontweight', 'bold', ...
                                   'units', 'normalized', ...
                                   'position', [0.01 0.84 0.15 0.15]);

    g_h_min_cover_rate_label = uicontrol('parent', g_h_cover_rate_panel, ...
                                         'style', 'text', ...
                                         'units', 'normalized', ...
                                         'position', [0.05 0.8 0.9 0.2], ...
                                         'fontsize', 11, ...
                                         'string', sprintf('Minimum = %.2f', min(frags_cover_rate)));

    g_h_max_cover_rate_label = uicontrol('parent', g_h_cover_rate_panel, ...
                                         'style', 'text', ...
                                         'units', 'normalized', ...
                                         'position', [0.05 0.55 0.9 0.2], ...
                                         'fontsize', 11, ...
                                         'string', sprintf('Maximum = %.2f', max(frags_cover_rate)));

    g_h_mean_cover_rate_label = uicontrol('parent', g_h_cover_rate_panel, ...
                                         'style', 'text', ...
                                         'units', 'normalized', ...
                                         'position', [0.05 0.3 0.9 0.2], ...
                                         'fontsize', 11, ...
                                         'string', sprintf('Mean = %.2f', mean(frags_cover_rate)));

    g_h_std_cover_rate_label = uicontrol('parent', g_h_cover_rate_panel, ...
                                         'style', 'text', ...
                                         'units', 'normalized', ...
                                         'position', [0.05 0.05 0.9 0.2], ...
                                         'fontsize', 11, ...
                                         'string', sprintf('Std = %.2f', std(frags_cover_rate)));

    %---------------------------

    g_h_frags_size_panel = uipanel('parent', g_fh_msm, ...
                                   'title', 'Size of fragments', ...
                                   'fontsize', 11, ...
                                   'fontweight', 'bold', ...
                                   'units', 'normalized', ...
                                   'position', [0.01 0.68 0.15 0.15]);

    g_h_min_size_label = uicontrol('parent', g_h_frags_size_panel, ...
                                         'style', 'text', ...
                                         'units', 'normalized', ...
                                         'position', [0.05 0.8 0.9 0.2], ...
                                         'fontsize', 11, ...
                                         'string', sprintf('Minimum = %.2f', min(frags_size)));

    g_h_max_size_label = uicontrol('parent', g_h_frags_size_panel, ...
                                   'style', 'text', ...
                                   'units', 'normalized', ...
                                   'position', [0.05 0.55 0.9 0.2], ...
                                   'fontsize', 11, ...
                                   'string', sprintf('Maximum = %.2f', max(frags_size)));

    g_h_mean_size_label = uicontrol('parent', g_h_frags_size_panel, ...
                                    'style', 'text', ...
                                    'units', 'normalized', ...
                                    'position', [0.05 0.3 0.9 0.2], ...
                                    'fontsize', 11, ...
                                    'string', sprintf('Mean = %.2f', mean(frags_size)));

    g_h_std_size_label = uicontrol('parent', g_h_frags_size_panel, ...
                                   'style', 'text', ...
                                   'units', 'normalized', ...
                                   'position', [0.05 0.05 0.9 0.2], ...
                                   'fontsize', 11, ...
                                   'string', sprintf('Std = %.2f', std(frags_size)));

    %---------------------------

    g_h_contrast_panel = uipanel('parent', g_fh_msm, ...
                                 'title', 'Contrast of fragments', ...
                                 'fontsize', 11, ...
                                 'fontweight', 'bold', ...
                                 'units', 'normalized', ...
                                 'position', [0.01 0.52 0.15 0.15]);

    g_h_min_contrast_label = uicontrol('parent', g_h_contrast_panel, ...
                                       'style', 'text', ...
                                       'units', 'normalized', ...
                                       'position', [0.05 0.8 0.9 0.2], ...
                                       'fontsize', 11, ...
                                       'string', sprintf('Minimum = %.2f', min(frags_contrast)));

    g_h_max_contrast_label = uicontrol('parent', g_h_contrast_panel, ...
                                       'style', 'text', ...
                                       'units', 'normalized', ...
                                       'position', [0.05 0.55 0.9 0.2], ...
                                       'fontsize', 11, ...
                                       'string', sprintf('Maximum = %.2f', max(frags_contrast)));

    g_h_mean_contrast_label = uicontrol('parent', g_h_contrast_panel, ...
                                        'style', 'text', ...
                                        'units', 'normalized', ...
                                        'position', [0.05 0.3 0.9 0.2], ...
                                        'fontsize', 11, ...
                                        'string', sprintf('Mean = %.2f', mean(frags_contrast)));

    g_h_std_contrast_label = uicontrol('parent', g_h_contrast_panel, ...
                                       'style', 'text', ...
                                       'units', 'normalized', ...
                                       'position', [0.05 0.05 0.9 0.2], ...
                                       'fontsize', 11, ...
                                       'string', sprintf('Std = %.2f', std(frags_contrast)));

    %---------------------------

    % We block the window
    uiwait(g_fh_msm);

    %----------------------------------------------------------------------
    %-------------------------------- Misc. -------------------------------
    %----------------------------------------------------------------------

    function [frags_cover_rate,frags_size,frags_contrast] = compute_measurements()
        % We get information about selected solution
        frag_sol      = g_mydata.frags_sols{g_mydata.current_recs_idx};
        im_rec_filled = g_mydata.im_recs_filled{g_mydata.current_recs_idx};

        % We get cover rate of fragments
        frags_cover_rate = zeros(1,numel(frag_sol));

        for k=1:numel(frag_sol)
            im_tmp              = (im_rec_filled==k);
            frags_cover_rate(k) = sum(im_tmp(:))/numel(im_rec_filled)*100.0;
        end

        % We compute statistics on size of fragments
        frags_size = cellfun(@(x) 2*x.outer_circle_radius, frag_sol);

        % We compute statistics on contrast of fragments
        frags_contrast = cellfun(@(x) x.std, frag_sol);
    end

    %----------------------------------------------------------------------
    %----------------------------- Callbacks ------------------------------
    %----------------------------------------------------------------------

    function quit_callback( h_object, event_data )
        delete(g_fh_msm);
    end
end