% This function opens a subwindow and deal with comparing a fresco reconstruction against a reference one
function arteak_comparison( fh_main )
    % We get GUI data
    g_mydata = guidata(fh_main);

    % We check if all inputs are available
    if numel(g_mydata.im_recs_color)<2 || numel(g_mydata.im_recs_alpha)<2
        uiwait(errordlg('At least two reconstructed frescoes must be previsously loaded', 'ARTEAK ERROR', 'modal'));
        return;
    end

    % Global settings
    g_translation_tolerance = 10.0; % in pixels
    g_rotation_tolerance    = 5.0;  % in degrees
    g_inaccurates_color     = g_mydata.colormap(15, :);
    g_true_positives_color  = g_mydata.colormap(4, :);
    g_false_positives_color = g_mydata.colormap(3, :);
    g_image_view            = [0.17 0.02 0.82 0.96];
    g_current_rec_idx       = -1;
    g_current_gt_idx        = -1;
    g_show_frags_idx        = true;
    g_show_frags_center     = true;
    g_show_frags_neighbors  = false;

    % We create the subwindow
    g_fh_cmp = figure('menubar', 'none', ...
                      'toolbar', 'none', ...
                      'color', get(0, 'defaultuicontrolbackgroundcolor'), ...
                      'name', 'ARTEAK - Comparison', ...
                      'units', 'normalized', ...
                      'position', [0 0 1 1], ...
                      'closerequestfcn', @quit_callback);

    g_h_quit_button = uicontrol('parent', g_fh_cmp, ...
                                'units', 'normalized', ...
                                'position', [0.01 0.01 0.15 0.04], ...
                                'style', 'pushbutton', ...
                                'fontsize', 11, ...
                                'string', 'Quit', ...
                                'handlevisibility', 'callback', ...
                                'callback', @quit_callback);

    %---------------------------

    g_h_recs_panel = uipanel('parent', g_fh_cmp, ...
                             'title', 'Reconstructed frescoes', ...
                             'fontsize', 11, ...
                             'fontweight', 'bold', ...
                             'units', 'normalized', ...
                             'position', [0.01 0.84 0.15 0.15]);

    g_h_recs_listbox = uicontrol('parent', g_h_recs_panel, ...
                                 'units', 'normalized', ...
                                 'position', [0.05 0.1 0.9 0.85], ...
                                 'style', 'listbox', ...
                                 'fontsize', 11, ...
                                 'string', {}, ...
                                 'handlevisibility', 'callback', ...
                                 'callback', @list_changed_callback);

    %---------------------------

    g_h_gt_panel = uipanel('parent', g_fh_cmp, ...
                           'title', 'Ideal reconstructed frescoes', ...
                           'fontsize', 11, ...
                           'fontweight', 'bold', ...
                           'units', 'normalized', ...
                           'position', [0.01 0.68 0.15 0.15]);

    g_h_gt_listbox = uicontrol('parent', g_h_gt_panel, ...
                               'units', 'normalized', ...
                               'position', [0.05 0.1 0.9 0.85], ...
                               'style', 'listbox', ...
                               'fontsize', 11, ...
                               'string', {}, ...
                               'handlevisibility', 'callback', ...
                               'callback', @list_changed_callback);

    %---------------------------

    g_h_settings_panel = uipanel('parent', g_fh_cmp, ...
                                 'title', 'Settings', ...
                                 'fontsize', 11, ...
                                 'fontweight', 'bold', ...
                                 'units', 'normalized', ...
                                 'position', [0.01 0.37 0.15 0.3]);

    g_h_tt_label = uicontrol('parent', g_h_settings_panel, ...
                             'style', 'text', ...
                             'units', 'normalized', ...
                             'position', [0.01 0.87 0.6 0.07], ...
                             'fontsize', 11, ...
                             'horizontalalignment', 'right', ...
                             'tooltip', 'in pixels', ...
                             'string', 'Translation tolerance:');

    g_h_tt_edit = uicontrol('parent', g_h_settings_panel, ...
                            'units', 'normalized', ...
                            'position', [0.65 0.87 0.3 0.1], ...
                            'style', 'edit', ...
                            'string', g_translation_tolerance, ...
                            'fontsize', 11, ...
                            'handlevisibility', 'callback', ...
                            'callback', @translation_tolerance_callback);

    g_h_rt_label = uicontrol('parent', g_h_settings_panel, ...
                             'style', 'text', ...
                             'units', 'normalized', ...
                             'position', [0.01 0.75 0.6 0.07], ...
                             'fontsize', 11, ...
                             'horizontalalignment', 'right', ...
                             'tooltip', 'in degrees', ...
                             'string', 'Rotation tolerance:');

    g_h_rt_edit = uicontrol('parent', g_h_settings_panel, ...
                            'units', 'normalized', ...
                            'position', [0.65 0.75 0.3 0.1], ...
                            'style', 'edit', ...
                            'string', g_translation_tolerance, ...
                            'fontsize', 11, ...
                            'handlevisibility', 'callback', ...
                            'callback', @rotation_tolerance_callback);

    g_h_tp_color_label = uicontrol('parent', g_h_settings_panel, ...
                                   'style', 'text', ...
                                   'units', 'normalized', ...
                                   'position', [0.01 0.63 0.6 0.07], ...
                                   'fontsize', 11, ...
                                   'horizontalalignment', 'right', ...
                                   'string', 'True positives:');

    g_h_tp_color_button = uicontrol('parent', g_h_settings_panel, ...
                                    'units', 'normalized', ...
                                    'position', [0.75 0.63 0.08 0.08], ...
                                    'style', 'pushbutton', ...
                                    'fontsize', 11, ...
                                    'handlevisibility', 'callback', ...
                                    'string', ' ', ...
                                    'backgroundcolor', g_true_positives_color, ...
                                    'callback', @true_positives_color_callback);

    g_h_fp_color_label = uicontrol('parent', g_h_settings_panel, ...
                                   'style', 'text', ...
                                   'units', 'normalized', ...
                                   'position', [0.01 0.51 0.6 0.07], ...
                                   'fontsize', 11, ...
                                   'horizontalalignment', 'right', ...
                                   'string', 'False positives:');

    g_h_fp_color_button = uicontrol('parent', g_h_settings_panel, ...
                                    'units', 'normalized', ...
                                    'position', [0.75 0.51 0.08 0.08], ...
                                    'style', 'pushbutton', ...
                                    'fontsize', 11, ...
                                    'handlevisibility', 'callback', ...
                                    'string', ' ', ...
                                    'backgroundcolor', g_false_positives_color, ...
                                    'callback', @false_positives_color_callback);

    g_h_ina_color_label = uicontrol('parent', g_h_settings_panel, ...
                                    'style', 'text', ...
                                    'units', 'normalized', ...
                                    'position', [0.01 0.39 0.6 0.07], ...
                                    'fontsize', 11, ...
                                    'horizontalalignment', 'right', ...
                                    'string', 'Inaccurates:');

    g_h_ina_color_button = uicontrol('parent', g_h_settings_panel, ...
                                     'units', 'normalized', ...
                                     'position', [0.75 0.39 0.08 0.08], ...
                                     'style', 'pushbutton', ...
                                     'fontsize', 11, ...
                                     'handlevisibility', 'callback', ...
                                     'string', ' ', ...
                                     'backgroundcolor', g_inaccurates_color, ...
                                     'callback', @inaccurates_color_callback);

    g_h_frags_idx_label = uicontrol('parent', g_h_settings_panel, ...
                                    'style', 'text', ...
                                    'units', 'normalized', ...
                                    'position', [0.01 0.27 0.6 0.07], ...
                                    'fontsize', 11, ...
                                    'horizontalalignment', 'right', ...
                                    'string', 'Show frags idx:');

    g_h_frags_idx_checkbox = uicontrol('parent', g_h_settings_panel, ...
                                       'units', 'normalized', ...
                                       'position', [0.77 0.27 0.08 0.08], ...
                                       'style', 'checkbox', ...
                                       'fontsize', 11, ...
                                       'handlevisibility', 'callback', ...
                                       'value', g_show_frags_idx, ...
                                       'callback', @frags_idx_callback);

    g_h_frags_center_label = uicontrol('parent', g_h_settings_panel, ...
                                       'style', 'text', ...
                                       'units', 'normalized', ...
                                       'position', [0.01 0.15 0.6 0.07], ...
                                       'fontsize', 11, ...
                                       'horizontalalignment', 'right', ...
                                       'string', 'Show frags center:');

    g_h_frags_center_checkbox = uicontrol('parent', g_h_settings_panel, ...
                                          'units', 'normalized', ...
                                          'position', [0.77 0.15 0.08 0.08], ...
                                          'style', 'checkbox', ...
                                          'fontsize', 11, ...
                                          'handlevisibility', 'callback', ...
                                          'value', g_show_frags_center, ...
                                          'callback', @frags_center_callback);

    g_h_frags_neighbors_label = uicontrol('parent', g_h_settings_panel, ...
                                          'style', 'text', ...
                                          'units', 'normalized', ...
                                          'position', [0.01 0.03 0.6 0.07], ...
                                          'fontsize', 11, ...
                                          'horizontalalignment', 'right', ...
                                          'string', 'Show frags neighbors:');

    g_h_frags_neighbors_checkbox = uicontrol('parent', g_h_settings_panel, ...
                                             'units', 'normalized', ...
                                             'position', [0.77 0.03 0.08 0.08], ...
                                             'style', 'checkbox', ...
                                             'fontsize', 11, ...
                                             'handlevisibility', 'callback', ...
                                             'value', g_show_frags_neighbors, ...
                                             'callback', @frags_neighbors_callback);

    %---------------------------

    g_h_measurements_panel = uipanel('parent', g_fh_cmp, ...
                                     'title', 'Measurements', ...
                                     'fontsize', 11, ...
                                     'fontweight', 'bold', ...
                                     'units', 'normalized', ...
                                     'position', [0.01 0.06 0.15 0.3]);

    g_h_tp_label1 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.01 0.81 0.5 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'right', ...
                              'string', 'True positives:');

    g_h_tp_label2 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.55 0.81 0.4 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'left', ...
                              'string', '');

    g_h_tn_label1 = uicontrol('parent', g_h_measurements_panel, ...
                               'style', 'text', ...
                               'units', 'normalized', ...
                               'position', [0.01 0.71 0.5 0.15], ...
                               'fontsize', 11, ...
                               'horizontalalignment', 'right', ...
                               'string', 'True negatives:');

    g_h_tn_label2 = uicontrol('parent', g_h_measurements_panel, ...
                               'style', 'text', ...
                               'units', 'normalized', ...
                               'position', [0.55 0.71 0.4 0.15], ...
                               'fontsize', 11, ...
                               'horizontalalignment', 'left', ...
                               'string', '');

    g_h_fp_label1 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.01 0.61 0.5 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'right', ...
                              'string', 'False positives:');

    g_h_fp_label2 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.55 0.61 0.4 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'left', ...
                              'string', '');

    g_h_fn_label1 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.01 0.51 0.5 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'right', ...
                              'string', 'False negatives:');

    g_h_fn_label2 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.55 0.51 0.4 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'left', ...
                              'string', '');

    g_h_ina_label1 = uicontrol('parent', g_h_measurements_panel, ...
                               'style', 'text', ...
                               'units', 'normalized', ...
                               'position', [0.01 0.41 0.5 0.15], ...
                               'fontsize', 11, ...
                               'horizontalalignment', 'right', ...
                               'string', 'Inaccurates:');

    g_h_ina_label2 = uicontrol('parent', g_h_measurements_panel, ...
                               'style', 'text', ...
                               'units', 'normalized', ...
                               'position', [0.55 0.41 0.4 0.15], ...
                               'fontsize', 11, ...
                               'horizontalalignment', 'left', ...
                               'string', '');

    g_h_acc_label1 = uicontrol('parent', g_h_measurements_panel, ...
                               'style', 'text', ...
                               'units', 'normalized', ...
                               'position', [0.01 0.31 0.5 0.15], ...
                               'fontsize', 11, ...
                               'horizontalalignment', 'right', ...
                               'string', 'Accuracy (%):');

    g_h_acc_label2 = uicontrol('parent', g_h_measurements_panel, ...
                               'style', 'text', ...
                               'units', 'normalized', ...
                               'position', [0.55 0.31 0.4 0.15], ...
                               'fontsize', 11, ...
                               'horizontalalignment', 'left', ...
                               'string', '');

    g_h_fm_label1 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.01 0.21 0.5 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'right', ...
                              'string', 'F-measure (%):');

    g_h_fm_label2 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.55 0.21 0.4 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'left', ...
                              'string', '');

    g_h_te_label1 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.01 0.11 0.5 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'right', ...
                              'string', 'Translation error:');

    g_h_te_label2 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.55 0.11 0.4 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'left', ...
                              'string', '');

    g_h_re_label1 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.01 0.01 0.5 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'right', ...
                              'string', 'Rotation error:');

    g_h_re_label2 = uicontrol('parent', g_h_measurements_panel, ...
                              'style', 'text', ...
                              'units', 'normalized', ...
                              'position', [0.55 0.01 0.4 0.15], ...
                              'fontsize', 11, ...
                              'horizontalalignment', 'left', ...
                              'string', '');

    %---------------------------

    %uiwait(g_fh_cmp);
    %return;

    % We define the portion of the figure where images are displayed
    g_axes = axes('position', g_image_view);
    axis off;

    % We fill lists with reconstructed fresco names from main window
    g_current_rec_idx = 1;
    set(g_h_recs_listbox, 'string', get(g_mydata.recs_listbox, 'string'));
    set(g_h_recs_listbox, 'value', g_current_rec_idx);

    g_current_gt_idx = 2;
    set(g_h_gt_listbox, 'string', get(g_mydata.recs_listbox, 'string'));
    set(g_h_gt_listbox, 'value', g_current_gt_idx);

    % We compare reconstructed frescoes and show their differences
    list_changed_callback([], []);

    % We block the window
    uiwait(g_fh_cmp);

    %----------------------------------------------------------------------
    %-------------------------------- Misc. -------------------------------
    %----------------------------------------------------------------------

    function update_view( tp, fp, tn, fn, te, re, ina, im_rec_color, im_rec_alpha )
        figure(g_fh_cmp);

        if isempty(im_rec_color) || isempty(im_rec_alpha)
            cla(g_axes);
        end

        image(g_axes, im_rec_color, 'AlphaData', im_rec_alpha);
        set(g_axes, 'visible', 'off');
        set(g_axes, 'color', 'none');
        axis image;

        hold on;

        frags_sol     = g_mydata.frags_sols{g_current_rec_idx};
        default_color = g_mydata.colormap(8,:);

        for k=1:length(frags_sol)
            idx         = frags_sol{k}.idx;
            icc         = frags_sol{k}.inner_circle_center;
            icr         = frags_sol{k}.inner_circle_radius;
            translation = frags_sol{k}.translation;
            angle       = frags_sol{k}.angle;
            frag_size   = size(g_mydata.frags_infos{idx}.alpha);

            if isempty(tp) && isempty(fp) && isempty(tn) && isempty(fn) && isempty(ina)
                color = default_color;
            else
                if ~isempty(ina) && sum(ina==idx)==1
                    color = g_inaccurates_color;
                elseif ~isempty(fp) && sum(fp==idx)==1
                    color = g_false_positives_color;
                else
                    color = g_true_positives_color;
                end
            end

            p = apply_forward_transform(icc, translation, angle, frag_size*0.5);

            if g_show_frags_idx
                text(double(p(2)+10), double(p(1)+10), sprintf('%d', idx-1), 'Color', color, 'FontSize', 12);
            end

            if g_show_frags_center
                plot(p(2), p(1), 'r+', 'MarkerSize', 0.5*icr, 'Color', color, 'LineWidth', 2);
            end

            if g_show_frags_neighbors
                numel(frags_sol{k}.neighbors)
                for i=1:numel(frags_sol{k}.neighbors)
                    idx2         = frags_sol{k}.neighbors(i);
                    j            = find(cellfun(@(x) x.idx, frags_sol)==idx2);
                    icc2         = frags_sol{j}.inner_circle_center;
                    translation2 = frags_sol{j}.translation;
                    angle2       = frags_sol{j}.angle;
                    frag_size    = size(g_mydata.frags_infos{idx2}.alpha);
                    p            = apply_forward_transform(icc2, translation, angle, frag_size*0.5);
                    plot([p(2),p(2)], [p(1),p(1)], 'g-', 'LineWidth', 2, 'Color', default_color);
                end
            end
        end

        hold off;

        axtoolbar(g_axes, {'zoomin','zoomout','restoreview','datacursor','pan','export'});
    end

    %----------------------------------------------------------------------
    %----------------------------- Callbacks ------------------------------
    %----------------------------------------------------------------------

    function list_changed_callback( h_object, event_data )
        % We update current indexes of lists
        g_current_rec_idx = get(g_h_recs_listbox, 'Value');
        g_current_gt_idx  = get(g_h_gt_listbox, 'Value');

        % We check if reconstructed frescoes are the same
        if g_current_rec_idx==g_current_gt_idx
            % If so, we set measurements as empty
            set(g_h_tp_label2, 'string', '');
            set(g_h_fp_label2, 'string', '');
            set(g_h_tn_label2, 'string', '');
            set(g_h_fn_label2, 'string', '');
            set(g_h_ina_label2, 'string', '');
            set(g_h_acc_label2, 'string', '');
            set(g_h_fm_label2, 'string', '');
            set(g_h_te_label2, 'string', '');
            set(g_h_re_label2, 'string', '');
            update_view([], [], [], [], [], [], [], []);
            return;
        end

        % We compare current reconstructed fresco against the current ideal one
        [tp,fp,tn,fn,acc,fm,te,re,ina] = compare_solution_to_gt(g_mydata.frags_sols{g_current_rec_idx}, ...
                                                                         g_mydata.frags_sols{g_current_gt_idx}, ...
                                                                         numel(g_mydata.frags_infos), ...
                                                                         g_translation_tolerance, ...
                                                                         g_rotation_tolerance);

        % We set measurements in respective fields
        set(g_h_tp_label2, 'string', sprintf('%d', numel(tp)));
        set(g_h_fp_label2, 'string', sprintf('%d', numel(fp)));
        set(g_h_tn_label2, 'string', sprintf('%d', numel(tn)));
        set(g_h_fn_label2, 'string', sprintf('%d', numel(fn)));
        set(g_h_ina_label2, 'string', sprintf('%d', numel(ina)));
        set(g_h_acc_label2, 'string', sprintf('%.2f', acc));
        set(g_h_fm_label2, 'string', sprintf('%.2f', fm));
        set(g_h_te_label2, 'string', sprintf('%.2f+/-%.2f', mean(te(2,:)), std(te(2,:))));
        set(g_h_re_label2, 'string', sprintf('%.2f+/-%.2f', mean(re(2,:)), std(re(2,:))));

        % We update the image view
        update_view(tp, fp, tn, fn, te, re, ina, g_mydata.im_recs_color{g_current_rec_idx}, g_mydata.im_recs_alpha{g_current_rec_idx});
    end

    function translation_tolerance_callback( h_object, event_data )
        tt = str2num(get(g_h_tt_edit, 'string'));

        if isempty(tt)
            uiwait(errordlg('Translation tolerance must be a non empty numeric value', 'ARTEAK ERROR', 'modal'));
            return;
        end

        if tt<0.0
            uiwait(errordlg('Translation tolerance must be expressed in pixels and non-negative', 'ARTEAK ERROR', 'modal'));
            return;
        end

        g_translation_tolerance = tt;
        list_changed_callback([], []);
    end

    function rotation_tolerance_callback( h_object, event_data )
        rt = str2num(get(g_h_rt_edit, 'string'));

        if isempty(rt)
            uiwait(errordlg('Rotation tolerance must be a non empty numeric value', 'ARTEAK ERROR', 'modal'));
            return;
        end

        if rt<0.0
            uiwait(errordlg('Rotation tolerance must be expressed in degrees and non-negative', 'ARTEAK ERROR', 'modal'));
            return;
        end

        g_rotation_tolerance = rt;
        list_changed_callback([], []);
    end

    function true_positives_color_callback( h_object, event_data )
        g_true_positives_color = uisetcolor(g_true_positives_color);
        set(h_object, 'backgroundcolor', g_true_positives_color);
        list_changed_callback([], []);
    end

    function false_positives_color_callback( h_object, event_data )
        g_false_positives_color = uisetcolor(g_false_positives_color);
        set(h_object, 'backgroundcolor', g_false_positives_color);
        list_changed_callback([], []);
    end

    function inaccurates_color_callback( h_object, event_data )
        g_inaccurates_color = uisetcolor(g_inaccurates_color);
        set(h_object, 'backgroundcolor', g_inaccurates_color);
        list_changed_callback([], []);
    end

    function frags_idx_callback( h_object, event_data )
        g_show_frags_idx = ~g_show_frags_idx;
        list_changed_callback([], []);
    end

    function frags_center_callback( h_object, event_data )
        g_show_frags_center = ~g_show_frags_center;
        list_changed_callback([], []);
    end

    function frags_neighbors_callback( h_object, event_data )
        g_show_frags_neighbors = ~g_show_frags_neighbors;
        list_changed_callback([], []);
    end

    function quit_callback( h_object, event_data )
        delete(g_fh_cmp);
    end
end