% This function opens a subwindow and deal with fresco reconstruction
function [new_frags_sol,new_im_rec_color,new_im_rec_gray,rec_name] = arteak_reconstruction( fh_main )
    % We get GUI data
    g_mydata = guidata(fh_main);

    % We check if all inputs are available
    if isempty(g_mydata.im_fresco) || numel(g_mydata.frags_infos)==0
        uiwait(errordlg('A fresco image a set of fragment images must be previously loaded', 'ARTEAK ERROR', 'modal'));
        return;
    end

    % We make as empty returned variables
    new_frags_sol    = {};
    new_im_rec_color = [];
    new_im_rec_gray  = [];
    rec_name         = '';

    % Global variables
    g_parameters = {struct('label', 'beta_{d}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                    struct('label', 'beta_{inc}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                    struct('label', 'beta_{c}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                    struct('label', 'beta_{no}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                    struct('label', 'beta_{sf}', 'type', 'numeric', 'value', '1.0', 'min', '0.0'), ...
                    struct('label', 'lambda', 'type', 'numeric', 'value', '1.0', 'min', '0.00000001'), ...
                    struct('label', 'mu', 'type', 'numeric', 'value', '1.0', 'min', '-1.0', 'max', '1.0'), ...
                    struct('label', 'mu_{sf}', 'type', 'numeric', 'value', '1.0', 'min', '0.00000001'), ...
                    struct('label', 'm_{df}', 'type', 'numeric', 'value', '1.0', 'min', '0.00000001'), ...
                    struct('label', 'Nb iterations', 'type', 'numeric', 'value', '1', 'min', '0'), ...
                    struct('label', 'Nb fragments', 'type', 'numeric', 'value', '1', 'min', '1'), ...
                    struct('label', 'Fresco name', 'type', 'string', 'value', 'my_fresco')};

    % We create the subwindow
    g_fh_rec = figure('menubar', 'none', ...
                      'toolbar', 'none', ...
                      'color', get(0, 'defaultuicontrolbackgroundcolor'), ...
                      'name', 'ARTEAK - Reconstruction', ...
                      'units', 'normalized', ...
                      'position', [0 0 1 1], ...
                      'closerequestfcn', @quit_callback);

    g_parameters_panel = uipanel('parent', g_fh_rec, ...
                                 'title', 'Parameters', ...
                                 'fontsize', 11, ...
                                 'fontweight', 'bold', ...
                                 'units', 'normalized', ...
                                 'position', [0.01 0.35 0.3 0.6]);

    g_parameters_label = cell(1,numel(g_parameters));
    g_parameters_edit  = cell(1,numel(g_parameters));

    for k=1:numel(g_parameters)
        g_parameters_label{k} = uicontrol('parent', g_parameters_panel, ...
                                          'style', 'text', ...
                                          'units', 'normalized', ...
                                          'position', [0.05 0.92-(k-1)/numel(g_parameters) 0.25 0.06], ...
                                          'fontsize', 11, ...
                                          'horizontalalignment', 'right', ...
                                          'string', [g_parameters{k}.label ':']);

         g_parameters_edit{k} = uicontrol('parent', g_parameters_panel, ...
                                          'style', 'edit', ...
                                          'tag', sprintf('%d', k), ...
                                          'units', 'normalized', ...
                                          'position', [0.35 0.92-(k-1)/numel(g_parameters)+0.02 0.6 0.06], ...
                                          'fontsize', 11, ...
                                          'string', g_parameters{k}.value, ...
                                          'handlevisibility', 'callback', ...
                                          'callback', @parameters_callback);
    end

    g_h_reconstruct_button = uicontrol('parent', g_fh_rec, ...
                                       'units', 'normalized', ...
                                       'position', [0.01 0.06 0.3 0.04], ...
                                       'style', 'pushbutton', ...
                                       'fontsize', 11, ...
                                       'string', 'Reconstruct fresco', ...
                                       'handlevisibility', 'callback', ...
                                       'callback', @reconstruct_callback);

    g_h_quit_button = uicontrol('parent', g_fh_rec, ...
                                'units', 'normalized', ...
                                'position', [0.01 0.01 0.3 0.04], ...
                                'style', 'pushbutton', ...
                                'fontsize', 11, ...
                                'string', 'Quit', ...
                                'handlevisibility', 'callback', ...
                                'callback', @quit_callback);

    %---------------------------

    % We block the window
    uiwait(g_fh_rec);

    %----------------------------------------------------------------------
    %----------------------------- Callbacks ------------------------------
    %----------------------------------------------------------------------

    function err = parameters_callback( h_object, event_data )
        tag   = str2num(get(h_object, 'tag'));
        input = get(h_object, 'string');
        label = g_parameters{tag}.label;
        err   = false;

        if strcmp(g_parameters{tag}.type, 'numeric')
            input = str2num(input);

            if ~isnumeric(input)
                uiwait(errordlg(sprintf('Parameter %s must be numeric', label), 'ARTEAK ERROR', 'modal'));
                err = true;
                return;
            end

            if isfield(g_parameters{tag}, 'min') && input<str2num(g_parameters{tag}.min)
                uiwait(errordlg(sprintf('Parameter %s must be >= %f', label, g_parameters{tag}.min), 'ARTEAK ERROR', 'modal'));
                err = true;
                return;
            end

            if isfield(g_parameters{tag}, 'max') && input>str2num(g_parameters{tag}.max)
                uiwait(errordlg(sprintf('Parameter %s must be <= %f', label, g_parameters{tag}.max), 'ARTEAK ERROR', 'modal'));
                err = true;
                return;
            end
        elseif strcmp(g_parameters{tag}.type, 'string')
            if isempty(input)
                uiwait(errordlg(sprintf('Parameter %s must be a non empty string', label), 'ARTEAK ERROR', 'modal'));
                err = true;
                return;
            end
        else
            uiwait(errordlg(sprintf('Unknown type for parameter %s', label), 'ARTEAK ERROR', 'modal'));
            err = true;
            return;
        end
    end

    function reconstruct_callback( h_object, event_data )
        % We first check parameters
        for k=1:numel(g_parameters)
            if parameters_callback(g_parameters_edit{k}, [])
                return;
            end
        end

        % Then, we run fresco reconstruction and set output variables
        new_frags_sol    = g_mydata.frags_sols{g_mydata.current_recs_idx};
        new_im_rec_color = g_mydata.im_recs_color{g_mydata.current_recs_idx};
        new_im_rec_gray  = g_mydata.im_recs_gray{g_mydata.current_recs_idx};
        rec_name         = get(g_parameters_edit{k}, 'string');
        close(g_fh_rec);
    end

    function quit_callback( h_object, event_data )
        delete(g_fh_rec);
    end
end